### PR TITLE
update documentation for Medulla markdown pages

### PR DESCRIPTION
**Pull request by dariuswatson**
# Update documentation

- [ ] You've read the [Contributor Guide](https://github.com/recro/medulla/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/recro/medulla/blob/main/CODE_OF_CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Summary of the changes

Adding context into documents for Medulla, updating links with relative path to fix hyperlink to other .md documents

## Description

- Adding new context for "what is low-code" section

- Updating links to relative paths within architecture-overview.md
- The hyperlinks are being returned 404 
update example:
```bash
[here](dependencies/database-server)  --> [here](../dependencies/distributed-storage.md)
```

- Update image path to display in markdown document:
```bash
![High-Level Architecture](images/concepts/high-level-architecture.png) -->
![High-Level Architecture](../../images/concepts/high-level-architecture.png) 
```

## Fixes #{186}
- [Medulla Issue #186](https://github.com/recro/medulla/issues/186)

### CODE REVIEW

**Comment by AndrewBabbitt97** [comment]
@dariuswatson Can we get a `404.html` page added to the document root as a part of this?

It should just be a copy of index.html and added into the pipeline, this would fix direct links on GitHub pages. Should be done just after the build step.

**Comment by AndrewBabbitt97** [comment]
Actually.... I just noticed we already do that.... GitHub pages isn't picking up the 404.html doc for some reason and I'm not entirely sure why ATM. If it's a simple fix we should try to get it added.

**Comment by AndrewBabbitt97** [comment]
I found it... The pipeline needs to just move 404.html up one directory level and it should work

**Comment by dariuswatson** [comment]
Ah ok, thanks @AndrewBabbitt97

**Pull request closed without merging**
