### PR TITLE
feat: Working app

### PR DESCRIPTION
**Pull request by keithlogan94**
# Working app

- [ ] You've read the [Contributor Guide](https://github.com/recro/medulla/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/recro/medulla/blob/main/CODE_OF_CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Summary of the changes

{Summary} (Less than 80 characters)

## Description

{Detail}

Fixes #{issue number}

### CODE REVIEW

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 the linting is forcing me to write comments on code that we already know we are going to remove from the application because it's Kubernetes CRDs or related.

I don't want to write comments on code we know is going to be deleted.

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 can you make it so missing xml comments do not cause failed checks?

**Comment by AndrewBabbitt97** [comment]
Seems to mostly be CRD resources for commenting.... We aren't getting rid of the fields even if we transpose it into a database no? If so then the comments would still be of value as they will just be transposed into database models

**Comment by AndrewBabbitt97** [comment]
We will not be disabling inline documentation requirements for public APIs. If you don't want to do documentation comments on something it should be marked as `internal` or `private` as it isn't exposed publicly.

The plan is to align similarly to many other linters, code comments are generally a requirement no matter the language.

**Comment by keithlogan94** [comment]
The most efficient way would be to remove all that code now, and refactor it to database.

**Pull request closed without merging**
