### PR TITLE
fix: include libraries

### LINKED ISSUE #7: Add include for libraries
## Describe the bug
There is a missing reference to the library in the code

## To Reproduce
Rider is telling me not including these libraries is a bug

## Expected behavior

Rider is telling me not including these libraries is a bug

## Screenshots
Rider is telling me not including these libraries is a bug

## Additional context
Rider is telling me not including these libraries is a bug

### PR DESCRIPTION
**Pull request by keithlogan94**
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for your PR that you are making. Please open an issue to dicuss changes or new features.

**PR Title**
Added include libraries

**PR Description**
Added include libraries

Fixes #7

### CODE REVIEW

**Comment by babanfaraj** [comment]
LGTM

**Comment by AndrewBabbitt97** [comment]
Looks like a bug in Rider. Code compiles without these meaning they aren't needed.

I'll double check this when I hop on in about an hour.

**Comment by AndrewBabbitt97** [comment]
unneeded
Definitely a bug in rider, this should be brought to their attention I'm just not sure what channels/how we go about doing so.

**Comment by AndrewBabbitt97** [comment]
@keithlogan94 

Fully confirmed, this is indeed a rider bug.

C# 10 / .NET 6 added a new global usings feature. You can read up on it [here](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#global-using-directives).

As for how this is causing rider to detect this as an error, .NET 6 Preview 7 (the latest preview release) added commonly used namespaces as global using's in web projects. You can see the tracking item at https://github.com/dotnet/aspnetcore/issues/32451 and the implementation in https://github.com/dotnet/sdk/pull/18459.

After a build you can open the file `src/Medulla.Frontend/Server/obj/Debug/net60/Medulla.Frontend.Server.ImplicitNamespaceImports.cs` which has the following content:
```csharp
// <autogenerated />
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::System.Net.Http.Json;
global using global::Microsoft.AspNetCore.Builder;
global using global::Microsoft.AspNetCore.Hosting;
global using global::Microsoft.AspNetCore.Http;
global using global::Microsoft.AspNetCore.Routing;
global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Hosting;
global using global::Microsoft.Extensions.Logging;
```

Rider does not appear to be analyzing this file for whatever reason while Visual Studio and VS Code both do. This should get fixed in a future rider update. Keep in mind Rider does not fully support .NET 6 yet, can check out their post on it [here](https://rider-support.jetbrains.com/hc/en-us/articles/360016096799-Support-for-the-Upcoming-NET-SDK-6-0). This is actually a  nice new feature in .NET 6, so would really like to embrace it.

Visual Studio 2022 & VS Code are fully supported and updated every month to support the latest preview sdk updates. This should be less of an issue as we get closer to the GA release of .NET 6 in November. RC1 will be out on the 14th.

Until a fix is added to rider we could either just have you guys ignore the bug in rider or we could add `<EnableDefaultGlobalUsings_Web>false</EnableDefaultGlobalUsings_Web>` into all csproj files and add all the usings manually.

Ideas/thoughts?

**Comment by AndrewBabbitt97** [comment]
Resolved with latest rider versions.

**Pull request closed without merging**
