### PR TITLE
feat: editor

### PR DESCRIPTION
**Pull request by keithlogan94**
Adding editor to main branch

### CODE REVIEW

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 Please Review this is ready

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 Why did the line numbers changed go from 200,000+ to 26,000+?

**Comment by AndrewBabbitt97** [comment]
Does it matter if it is still fully implemented? A ton of unneeded files were removed because of the move to RCL.

**Comment by keithlogan94** [comment]
Okay, just curious.

**Comment by AndrewBabbitt97** [comment]
Culprit was likely the redundant `medulla.css` file

**Review by AndrewBabbitt97 — APPROVED** [review]

**Pull request merged**
