### PR TITLE
ci: Release Workflow

### PR DESCRIPTION
**Pull request by keithlogan94**
# Tye

- [x] You've read the [Contributor Guide](https://github.com/recro/medulla/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/recro/medulla/blob/main/CODE_OF_CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Summary of the changes

Adds a release workflow

## Description

Adds a release workflow

### CODE REVIEW

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 When can you take a look at this?

**Comment by AndrewBabbitt97** [comment]
`.github\chabgelog.json` is referenced but is missing from the PR.

The release notes are generated but never updated on the release.

These items will need to be fixed before merge.

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 could you make that update to the code?

I really don't know what the issue is, but I know you could fix it really quck.

**Comment by keithlogan94** [comment]
Bump

**Pull request merged**
