### PR TITLE
refactor: removing Medulla Kubernetes Operator

### PR DESCRIPTION
**Pull request by keithlogan94**
# removing Medulla Kubernetes Operator

- [ ] You've read the [Contributor Guide](https://github.com/recro/medulla/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/recro/medulla/blob/main/CODE_OF_CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Summary of the changes

{Summary} (Less than 80 characters)

## Description

{Detail}

Fixes #{issue number}

### CODE REVIEW

**Comment by AndrewBabbitt97** [comment]
Need to remove the project from the solution.

**Comment by keithlogan94** [comment]
I think this one is ready, this is a general cleanup pr.

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 When can you take a look at this?

**Pull request merged**
